name: Test Workflow

on:
  workflow_dispatch:  #permet de declancher

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: npm run test
